### ISSUE TITLE
it does not work with ios 8

### ISSUE THREAD

**Issue by fyears** [t413/SMS-Tools#16]

**Comment by fyears** [comment]
I am wrong. It seems that it is because the sqlite version in my Python is too old. I install newer `pysqlite` library and import it as `from pysqlite2 import dbapi2 as sqlite3`, then it seems work.

**Comment by t413** [comment]
Pssw, I was worried when I saw this! Thanks Apple for keeping the same / compatible db format!

**Comment by fyears** [comment]
@t413 But please consider adding some code to check the sqlite version of python and try to update it if necessary. :-)

In fact, I am using not-old python 2.7.8, but still the sqlite included in python is not new enough.

I have to `pip install pysqlite` and then manually change ALL the `import sqlite3` to `from pysqlite2 import dbapi2 as sqlite3` in your code.

**Comment by m-urban** [comment]
Just in case that anyone stumbles over this thread: It's end of 2016 now, and I am afraid to report that my testing with iOS 9 was not successful today. It seems that the database schema has by changed quite a bit…
