### ISSUE TITLE
UnboundLocalError: local variable 'new_texts' referenced before assignment

### ISSUE THREAD

**Issue by damiencourousse** [t413/SMS-Tools#3]
hello,

I get an error with the following command:
$ python sms_db_importer.py data/mmssms.db data/android.db
is Android
Traceback (most recent call last):
  File "sms_db_importer.py", line 297, in <module>
    sms_main()
  File "sms_db_importer.py", line 50, in sms_main
    texts += new_texts
UnboundLocalError: local variable 'new_texts' referenced before assignment

By the way, the new_texts variable is not set if the code moves to the "elif "sms" in tableNames" case.

regards,
Damien

**Comment by t413** [comment]
Thanks Damien, sorry I wasn't working on this much at the time. It's fixed now!
